name: Build and test docker images

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['datascience-notebook', 'python-test-environment', 'smee-proxy', 'jenkins-inbound-agent', 'toolbox']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t ${{ matrix.image }}:latest ${{ matrix.image }}/.
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          version: latest
      - name: Install dependencies
        run: poetry install -v
      - name: Test docker image
        run: make test dir=${{ matrix.image }}
      - name: Lint python code
        run: make lint
